name: study_buddy
description: A local-first student productivity app built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
